### ISSUE TITLE
about input data

### ISSUE THREAD

**Issue by ghost** [QuantuMope/handeye-4dof#4]
hello sir, 
thank you very much about your work with the pubulic code.
however, i have met some problems about accuracy when I used own data.
Could you please help me about how to collect the data?
thank you

**Comment by QuantuMope** [comment]
Hello,

If you are having issues with accuracy, this may be due to the quality of the sampled data you are using.

First rule of thumb is the more (non-redundant) data, the better.
Secondly, make sure that samples are being recorded as accurately as possible. Something that can help with this is to make sure the robot comes to a halt for a few seconds before taking samples so that any shaking / transform lag can be prevented.
Lastly, make sure to collect data along widest possible range of the DOFs.
For example, if we are using a SCARA (x, y, z, yaw), we'd want to grab samples where we vary the DOFs as much as possible while still keeping the tag in the frame.

Hope this helps. I will close this issue. Feel free to reopen if the above doesn't work.
